version: "3.8"

services:
  mongodb:
    build:
      context: ./
      dockerfile: ./docker/mongo
    container_name: mongoFocal
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - './db_data/db:/data/db'
      - './db_data/configdb:/data/configdb'

  app:
    depends_on:
      - mongodb
    build:
      context: ./
      dockerfile: ./docker/node
    container_name: appNode
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    env_file: ./.env   
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    stdin_open: true
    tty: true
volumes:
  node_modules:
    driver: local    